services:
  - type: web
    name: vmd-ai-meeting-companion
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/simple-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
